spring:


  datasource:
    username: root
    password: root
    url: jdbc:mysql://172.31.8.234:9005/Restaurant?userUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 172.31.8.234
    port: 6379

  session:
    timeout: 86400
    store-type: redis
    redis:
      flush-mode: on-save


server:
  port: 9001
  servlet:
    session:
      timeout: 86400m


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml  #classpath*:/

  global-config:
    db-config:
      id-type: auto    #auto increase


